---
name: Publish to PyPI

on:
  push:
    tags:
      - '*'
jobs:
  build_and_publish:
    name: Build Python distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
         python-version: 3.11
      - name: Install pypa/build
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine build
          python -m pip install importlib_metadata numpy pandas seaborn scipy tables tdt xlsxwriter
      #- name: Create dist directory
      #  run: mkdir -p dist      
      - name: Print Working Directory
        run: pwd  # This command prints the current working directory
      - name: List directories
        run: |
         echo "Listing directories in current working directory:"
         ls -d */
      - name: Extract version number from tag
        id: extract_version
        run: |
         echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
      - name: Build package
        run: |
         python -m build --sdist --wheel --version ${{ steps.extract_version.outputs.version }} --verbose > build_output.txt 2>&1
      - name: Display build output
        run: cat build_output.txt

      - name: List directory contents
        run: |
          echo "Listing contents of dist directory:"
          ls -lR dist
          echo "Listing contents of current directory:"
          ls -l
      - name: Upload distribution files
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  pypi-publish:
    needs: build_and_publish
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/fibphoflow
    permissions:
        contents: read
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps: # retrieve your distributions here
      - name: Download distribution files
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
